if(NOT DEFINED NUM8LORA_SOURCE_DIR OR NOT DEFINED NUM8LORA_TEST_BUILD_DIR OR NOT DEFINED NUM8LORA_MISSING_NUM8_ROOT)
    message(FATAL_ERROR "missing test paths")
endif()

file(REMOVE_RECURSE "${NUM8LORA_TEST_BUILD_DIR}")
execute_process(
    COMMAND "${CMAKE_COMMAND}" -S "${NUM8LORA_SOURCE_DIR}" -B "${NUM8LORA_TEST_BUILD_DIR}" -DNUM8LORA_BUILD_NUM8_ADAPTER=ON -DNUM8LORA_NUM8_ROOT=${NUM8LORA_MISSING_NUM8_ROOT} -DCMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION=10.0.22621.0
    RESULT_VARIABLE configure_result
    OUTPUT_QUIET
    ERROR_QUIET)
if(configure_result EQUAL 0)
    message(FATAL_ERROR "adapter request unexpectedly configured successfully")
endif()
